#!/usr/bin/env bash

mkdir build

for file in $(find . -name "*.crd" | sort);
do
    name=$(basename $file)
    TMP=$(mktemp)
    title=$(sed -n 1p "$file" \
        | sed -e 's/{title: //' \
        | sed -e 's/}$//')
    artist=$(sed -n 2p "$file" \
        | sed -e 's/{artist: //' \
        | sed -e 's/}$//')
    echo -n \# $artist - $title >> "$TMP"
    cat "$file" | \
        sed -e 's@\[\([a-zA-Z]+\)\]@\\chord{\1}@g' | \
        sed -e 's/{soc}/\\begin{chorus}/' | \
        sed -e 's/{eoc}/\\end{chorus}/' | \
        sed -e 's/{.*:.*}//' >> "$TMP"
    mv "$TMP" "build/${name%.crd}.md"
done


# \newcommand\chord[2][l]{%
#       \makebox[0pt][#1]{\begin{tabular}[b]{@{}l@{}}#2\\\mbox{}\end{tabular}}}

